name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    # Checkout the source code
    - name: Checkout
      uses: actions/checkout@v3
    
    # Install Go 1.20
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"
    
    # Build binaries for both Linux and Windows
    - name: Build for all platforms
      run: go mod download && go run build.go -release
    
    # If this is a tagged release then upload the release binaries
    - name: Upload release binaries
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./bin/bootnext-*
